services:
  app:
    container_name: code-judge-backend
    image: ghcr.io/cstria0106/code-judge-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file: .env.docker.app
    depends_on:
      - database
      - rabbitmq
    restart: always
  database:
    container_name: database
    image: mariadb:11
    volumes:
      - ./volumes/database/conf.d:/etc/mysql/conf.d
      - ./volumes/database/data:/var/lib/mysql
      - ./volumes/database/initdb.d:/docker-entrypoint-initdb.d
    env_file: .env.docker.db
    environment:
      TZ: UTC
    restart: always
    ports:
      - 3306:3306
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    volumes:
      - ./volumes/rabbitmq/data/:/var/lib/rabbitmq/
    ports:
      - '5672:5672'
      - '15672:15672'
    restart: always
    env_file: .env.docker.rmq
